title: The Newbe's Story
author: NewTech-bit
email: check@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog tells the story of a new GitHub user.


# social links
twitter_username: I don't have any # DO NOT include the @ character, or else the build will fail!
github_username:  NewTech-bit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
